### ISSUE TITLE
PWA

### ISSUE THREAD

**Issue by tohid-ab** [tohid-ab/iran-django-project#2]
How can I use pwa for my website?

**Comment by mobinghaemi** [comment]
Hi, just add the manifest.json file to the main folder of the project and put the following information inside it

{
    "name": "appName",
    "short_name": "short appName",
    "start_url": ".",
    "background_color": "#0c151d",
    "theme_color": "#0c151d",
    "display": "standalone",
    "icons": [
        {
            "src": "images/icon.png",
            "sizes": "192x192",
            "type": "image/png"
        },
        {
            "src": "images/icon.png",
            "sizes": "512x512",
            "type": "image/png"
        }
    ]
}

Good Luck!
